# Generated by Django 5.1.6 on 2025-02-17 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Comic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("date_published", models.DateField()),
                ("link", models.URLField()),
                ("writers", models.CharField(max_length=255)),
                ("artists", models.CharField(max_length=255)),
                ("number_issues", models.IntegerField()),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
