# Generated by Django 5.1.6 on 2025-02-20 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="page_number",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
