# Generated by Django 5.1.6 on 2025-02-20 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comics", "0003_alter_page_image_link"),
    ]

    operations = [
        migrations.CreateModel(
            name="DownloadJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("downloaded_pages", models.IntegerField()),
                ("total_pages", models.IntegerField()),
                ("folder_name", models.CharField(max_length=255)),
                ("complete", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="DownloadJobStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("issue_folder_name", models.CharField(max_length=255)),
                ("complete", models.BooleanField()),
                (
                    "download_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="download_job_steps",
                        to="comics.downloadjob",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="download_job_steps",
                        to="comics.page",
                    ),
                ),
            ],
        ),
    ]
