# Generated by Django 5.1.6 on 2025-02-20 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comics", "0004_downloadjob_downloadjobstep"),
    ]

    operations = [
        migrations.AddField(
            model_name="downloadjob",
            name="total_issues",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
