# Generated by Django 5.1.6 on 2025-02-20 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comics", "0005_downloadjob_total_issues"),
    ]

    operations = [
        migrations.AddField(
            model_name="downloadjobstep",
            name="image_link",
            field=models.URLField(default="", max_length=500, unique=True),
            preserve_default=False,
        ),
    ]
