# Generated by Django 5.1.6 on 2025-02-20 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comics", "0006_downloadjobstep_image_link"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="downloadjobstep",
            name="issue_folder_name",
        ),
        migrations.AddField(
            model_name="downloadjobstep",
            name="issue_index_number",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="downloadjobstep",
            name="page_number",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
