# Generated by Django 5.1.6 on 2025-02-20 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comics", "0007_remove_downloadjobstep_issue_folder_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="downloadjob",
            name="folder_name",
        ),
    ]
