# Generated by Django 5.1.6 on 2025-02-24 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comics", "0008_remove_downloadjob_folder_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="downloadjob",
            name="name",
            field=models.CharField(default="default", max_length=255),
            preserve_default=False,
        ),
    ]
