# Generated by Django 5.1.6 on 2025-02-25 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comics", "0009_downloadjob_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="downloadjobstep",
            name="image_link",
            field=models.URLField(max_length=500),
        ),
    ]
