# Generated by Django 5.1.6 on 2025-03-01 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comics", "0010_alter_downloadjobstep_image_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="downloadjobstep",
            name="issue_link",
            field=models.URLField(default="", unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="downloadjobstep",
            name="retry",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
