# Generated by Django 5.1.6 on 2025-03-05 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comics", "0011_downloadjobstep_issue_link_downloadjobstep_retry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="downloadjobstep",
            name="issue_link",
            field=models.URLField(),
        ),
    ]
